blank_issues_enabled: false

contact_links:
  - name: Questions Telegram
    url: https://t.me/radare
    about: Please ask questions about Iaito in the radare telegram or IRC chat

  - name: Questions Discord
    url: https://discord.gg/MgEdxrMnqx
    about: "Official Discord server"
